=== JavierMarron/Ejercicios/Leng. Marcas/XML/Ejercicios/Ejercicio VII/listado.dtd
<!ELEMENT listado (futuro+, divisa+, bono+, letra+)>
        <!ATTLIST futuro precio CDATA #REQUIRED>
        <!ATTLIST divisa precio CDATA #REQUIRED>
        <!ATTLIST bono precio CDATA #REQUIRED>
        <!ATTLIST letra precio CDATA #REQUIRED>
        <!ELEMENT ciudad_procedencia (Madrid|NuevaYork|Frankfurt|Tokio)>
        <!ELEMENT Madrid EMPTY>
        <!ELEMENT NuevaYork EMPTY>
        <!ELEMENT Frankfurt EMPTY>
        <!ELEMENT Tokio EMPTY>
        <!ATTLIST divisa estable CDATA #IMPLIED>
        <!ATTLIST bono estable CDATA #IMPLIED>
        <!ELEMENT futuro (producto, mercado?, ciudad_procedencia)>
        <!ELEMENT producto (#PCDATA)>
        <!ELEMENT mercado (#PCDATA)>
        <!ELEMENT bono (pais_de_procedencia,valor_deseado, valor_minimo, valor_maximo, ciudad_procedencia)>
        <!ELEMENT valor_deseado (#PCDATA)>
        <!ELEMENT valor_minimo (#PCDATA)>
        <!ELEMENT valor_maximo (#PCDATA)>
        <!ELEMENT pais_de_procedencia (#PCDATA)>
        <!ELEMENT divisa (nombre_divisa, tipo_de_cambio+, ciudad_procedencia)>
        <!ELEMENT nombre_divisa (#PCDATA)>
        <!ELEMENT tipo_de_cambio (#PCDATA)>
        <!ELEMENT letra (tipo_de_interes, pais_emisor,ciudad_procedencia)>
        <!ELEMENT tipo_de_interes (#PCDATA)>
        <!ELEMENT pais_emisor (España|EEUU|Alemania|Japon)>
        <!ELEMENT España EMPTY>
        <!ELEMENT EEUU EMPTY>
        <!ELEMENT Alemania EMPTY>
        <!ELEMENT Japon EMPTY>

=== JavierMarron/Ejercicios/Leng. Marcas/XML/Ejercicios/Ejercicio VII/Ejercicio_VIII.xml
<?xml version="1.0"?>
<!DOCTYPE listado SYSTEM "listado.dtd">

<listado>
  <futuro precio="12.59">
    <producto>Hamburguesas</producto>
    <mercado>Europa</mercado>
    <ciudad_procedencia>
      <Frankfurt/>
    </ciudad_procedencia>
  </futuro>
  <divisa precio="1698">
    <nombre_divisa>Euro</nombre_divisa>
    <tipo_de_cambio>2.1:1 euros</tipo_de_cambio>
    <tipo_de_cambio>1:0.87 dólares</tipo_de_cambio>
    <ciudad_procedencia>
      <Madrid/>
    </ciudad_procedencia>
  </divisa>
  <bono precio="12940" estable="si">
    <pais_de_procedencia>
      Estados Unidos
    </pais_de_procedencia>
    <valor_deseado>1200</valor_deseado>
    <valor_minimo>3970</valor_minimo>
    <valor_maximo>18560</valor_maximo>
    <ciudad_procedencia>
      <Tokio/>
    </ciudad_procedencia>
  </bono>
  <letra precio="96310">
    <tipo_de_interes>7.83%</tipo_de_interes>
    <pais_emisor>
      <España/>
    </pais_emisor>
    <ciudad_procedencia>
      <Madrid/>
    </ciudad_procedencia>
  </letra>
</listado>
